pretrain: 
    id_or_url: 13327Y1tz1ohsm5YZMyXVMPIOjoOA0OaA
    md5: 9cc606b70460261de374c56548aead5b
    cached: /tmp/tranformerorc.pth

# url or local path
weights: https://drive.google.com/uc?id=13327Y1tz1ohsm5YZMyXVMPIOjoOA0OaA

backbone: vgg19_bn
cnn:
    # pooling stride size
    ss:
        - [2, 2]
        - [2, 2]
        - [2, 1]
        - [2, 1]
        - [1, 1]         
    # pooling kernel size 
    ks:
        - [2, 2]
        - [2, 2]
        - [2, 1]
        - [2, 1]
        - [1, 1]
    # dim of ouput feature map
    hidden: 256

